confluentinc/debezium

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnector.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorTest.java
Hotfix for #inc-rcca-1836-postgres-cdc-source-
> Catch and handle exception thrown in validation

- Jenkinsfile
- debezium-api/pom.xml
- debezium-connector-mongodb/pom.xml
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
- debezium-core/pom.xml
- debezium-ddl-parser/pom.xml
- debezium-embedded/pom.xml
- debezium-microbenchmark/pom.xml
- debezium-quarkus-outbox/pom.xml
- debezium-scripting/pom.xml
- debezium-server/pom.xml
- debezium-testing/pom.xml
- pom.xml
> Add a Jenkins file.

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnector.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorTest.java
Add validation for SQL Server connector.
> Add validation for SQL Server connector.

- debezium-connector-mysql/pom.xml
- debezium-connector-postgres/pom.xml
- debezium-connector-sqlserver/pom.xml
Add jacoco plugin for coverage report.
> Add jacoco plugin for coverage report.

- debezium-core/src/main/java/io/debezium/relational/history/KafkaDatabaseHistory.java
Close database history producer with timeout on stop.
> Close database history producer with timeout on stop.

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlValueConvertersTest.java
- debezium-core/src/main/java/io/debezium/jdbc/JdbcValueConverters.java
[Jira](https://confluentinc.atlassian.net/browse/CCDB-3848)
Cherry-picks the changes from https://github.com/debezium/debezium/pull/2278 onto our 1.3.1 hotfix branch so that the fix can be deployed into cloud.
> CCDB-3848: Adjust scale of fallback BigDecimal values to match column schema

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnector.java
Log full exception stack trace when connection test fails.
> Log full exception stack trace when connection test fails.

- debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java
- debezium-core/src/main/java/io/debezium/relational/history/KafkaDatabaseHistory.java
Removed logging for when configs are called with masked passwords.
> Remove logging for configs

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerChangeTablePointer.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerChangeTableSetIT.java
Problem 
https://issues.redhat.com/browse/DBZ-2716 
https://confluentinc.atlassian.net/browse/RCCA-3404
If customer is running connector against an out dated capture table, and it finds a column that no longer exists in the source table, an NPE is thrown.
Solution.
We should guard against this. I just cherry picked the change from upstream
> Cherry Pick: DBZ-2716 Guard against missing position mapping

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/legacy/AbstractReader.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/signal/KafkaSignalThread.java
- debezium-core/src/main/java/io/debezium/connector/base/ChangeEventQueue.java
- debezium-core/src/main/java/io/debezium/relational/history/FileDatabaseHistory.java
- debezium-core/src/main/java/io/debezium/relational/history/KafkaDatabaseHistory.java
- debezium-core/src/test/java/io/debezium/kafka/KafkaCluster.java
- debezium-server/debezium-server-eventhubs/src/main/java/io/debezium/server/eventhubs/EventHubsChangeConsumer.java
- debezium-server/debezium-server-kafka/src/main/java/io/debezium/server/kafka/KafkaChangeConsumer.java
- debezium-server/debezium-server-kinesis/src/main/java/io/debezium/server/kinesis/KinesisChangeConsumer.java
- debezium-server/debezium-server-pubsub/src/main/java/io/debezium/server/pubsub/PubSubChangeConsumer.java
- debezium-server/debezium-server-pulsar/src/main/java/io/debezium/server/pulsar/PulsarChangeConsumer.java
- debezium-server/debezium-server-redis/src/main/java/io/debezium/server/redis/RedisStreamChangeConsumer.java
https://confluentinc.atlassian.net/browse/RCCA-8792
> RCCA 8792: Remove logging of records in debug and trace logs

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/legacy/AbstractReader.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/signal/KafkaSignalThread.java
- debezium-core/src/main/java/io/debezium/connector/base/ChangeEventQueue.java
- debezium-core/src/main/java/io/debezium/relational/history/FileDatabaseHistory.java
- debezium-core/src/main/java/io/debezium/relational/history/KafkaDatabaseHistory.java
- debezium-core/src/test/java/io/debezium/kafka/KafkaCluster.java
- debezium-server/debezium-server-eventhubs/src/main/java/io/debezium/server/eventhubs/EventHubsChangeConsumer.java
- debezium-server/debezium-server-kafka/src/main/java/io/debezium/server/kafka/KafkaChangeConsumer.java
- debezium-server/debezium-server-kinesis/src/main/java/io/debezium/server/kinesis/KinesisChangeConsumer.java
- debezium-server/debezium-server-pubsub/src/main/java/io/debezium/server/pubsub/PubSubChangeConsumer.java
- debezium-server/debezium-server-pulsar/src/main/java/io/debezium/server/pulsar/PulsarChangeConsumer.java
(cherry picked from commit 125364367af5536659bbe1519b38fa56d75e809e)
https://confluentinc.atlassian.net/browse/RCCA-8792
> RCCA-8792: Remove logging of records in debug and trace logs

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
More details at https://issues.redhat.com/browse/DBZ-5988
> CCDB-5267: Impose null check on schema value prior to any operation

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresOffsetContext.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSnapshotChangeEventSource.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/SourceInfo.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/WalPositionLocator.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/SourceInfoTest.java
Cherry-picking https://github.com/debezium/debezium/pull/4152
> CCDB-5304 DBZ-5915: correctly determine the startStreamingLsn

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbTaskContext.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlTaskContext.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/legacy/MySqlTaskContext.java
- debezium-connector-postgres/pom.xml
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresTaskContext.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresMetricsIT.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerTaskContext.java
- debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java
- debezium-core/src/main/java/io/debezium/config/Field.java
- debezium-core/src/main/java/io/debezium/connector/common/CdcSourceTaskContext.java
- debezium-core/src/main/java/io/debezium/metrics/Metrics.java
- debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
We're backporting [this change](https://github.com/debezium/debezium/pull/4652) from debezium upstream as a part of https://confluentinc.atlassian.net/browse/CC-21259
> CC-21261: Backport changes for custom metric tags

- Jenkinsfile
- debezium-connector-mysql/pom.xml
- pom.xml
Adds jenkins pipeline to debezium.
Test Run -- 
https://jenkins.confluent.io/job/confluentinc-pr/job/debezium/view/change-requests/job/PR-40/45/
> Jenkins pipeline for debezium

- debezium-bom/pom.xml
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnector.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorTest.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TestHelper.java
- debezium-core/pom.xml
- debezium-core/src/main/java/io/debezium/connector/common/RelationalBaseSourceConnector.java
- debezium-core/src/main/java/io/debezium/transforms/outbox/EventRouterConfigDefinition.java
- debezium-core/src/main/java/io/debezium/transforms/outbox/EventRouterDelegate.java
- debezium-core/src/test/java/io/debezium/transforms/outbox/EventRouterTest.java
Cherry-picking the local changes for Postgres CDC in a single commit.
> Cherry-picked local changes for Postgres

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlStreamingChangeEventSource.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/BinlogReaderSanitizeAuthenticationExceptionTest.java
- debezium-connector-mysql/src/test/java/io/debezium/relational/history/KafkaSchemaHistoryTest.java
- debezium-core/src/main/java/io/debezium/config/Configuration.java
- debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java
- debezium-storage/debezium-storage-kafka/src/main/java/io/debezium/storage/kafka/history/KafkaSchemaHistory.java
Cherry-picking the local changes for MySql CDC in a single commit.
> Cherry-picked local changes for MySql

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbSnapshotChangeEventSource.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/outbox/MongoEventRouterTest.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/ReplicaIdentityMapper.java
- debezium-core/src/main/java/io/debezium/config/Configuration.java
- debezium-core/src/main/java/io/debezium/config/Field.java
- debezium-core/src/main/java/io/debezium/function/Predicates.java
- debezium-core/src/main/java/io/debezium/pipeline/signal/actions/snapshotting/AdditionalCondition.java
- debezium-core/src/main/java/io/debezium/pipeline/signal/actions/snapshotting/ExecuteSnapshot.java
- debezium-core/src/main/java/io/debezium/pipeline/source/AbstractSnapshotChangeEventSource.java
- debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotChangeEventSource.java
- debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalDatabaseConnectorConfig.java
- debezium-core/src/main/java/io/debezium/relational/Key.java
- debezium-core/src/main/java/io/debezium/relational/RelationalDatabaseConnectorConfig.java
- debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java
- debezium-core/src/main/java/io/debezium/relational/history/AbstractSchemaHistory.java
- debezium-core/src/main/java/io/debezium/relational/mapping/ColumnMappers.java
- debezium-core/src/main/java/io/debezium/schema/AbstractRegexTopicNamingStrategy.java
- debezium-core/src/main/java/io/debezium/transforms/ByLogicalTableRouter.java
- debezium-core/src/main/java/io/debezium/transforms/TimezoneConverter.java
- debezium-core/src/main/java/io/debezium/util/Strings.java
- debezium-core/src/test/java/io/debezium/config/ConfigurationTest.java
- debezium-core/src/test/java/io/debezium/util/StringsTest.java
Addresses https://confluentinc.atlassian.net/browse/CC-22779
> Changed java regex to Re2j

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/WalPositionLocator.java
Cherry-picking [DBZ-6204](https://github.com/debezium/debezium/pull/4357) as part of https://confluentinc.atlassian.net/browse/CC-21728
> Cherry-pick DBZ-6204

- COPYRIGHT.txt
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
- documentation/modules/ROOT/pages/connectors/postgresql.adoc
- jenkins-jobs/scripts/config/Aliases.txt
Cherry-picking [DBZ-3921](https://github.com/debezium/debezium/pull/3486) and [DBZ-6577](https://github.com/debezium/debezium/pull/4621) as part of https://confluentinc.atlassian.net/browse/CC-21728
> Cherry-pick DBZ-3921 and DBZ-6577

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/TypeRegistry.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresDefaultValueConverter.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/connection/PostgresDefaultValueConverterIT.java
Cherry-picking [DBZ-5038](https://github.com/debezium/debezium/pull/3520) as part of https://confluentinc.atlassian.net/browse/CC-21728
> Cherry-pick DBZ-5038

- COPYRIGHT.txt
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
- documentation/modules/ROOT/pages/connectors/postgresql.adoc
- jenkins-jobs/scripts/config/Aliases.txt
Reverts confluentinc/debezium#54
> Revert "Cherry-pick DBZ-3921 and DBZ-6577"

- .github/CODEOWNERS
- .semaphore/project.yml
- .semaphore/semaphore.yml
- Jenkinsfile
- debezium-connector-mysql/src/test/resources/docker/conf/mysql.cnf
- service.yml
- sonar-project.properties
[Read the background and motivation](https://confluentinc.atlassian.net/wiki/spaces/TOOLS/pages/3033867557/CI+System+Migration+Jenkins-+Semaphore#Background-and-Motivation)  
Please merge this PR ASAP because we plan on shutting down Jenkins by the end of the year.
> CC-24280 Jenkins migration 1.9.6

- .github/CODEOWNERS
- .semaphore/project.yml
- .semaphore/semaphore.yml
- Jenkinsfile
- debezium-connector-mysql/src/test/resources/docker/conf/mysql.cnf
- debezium-core/src/test/java/io/debezium/transforms/TimezoneConverterTest.java
- service.yml
- sonar-project.properties
chore: update repo codeowners [ci skip]
chore: update repo semaphore project
chore: update repo semaphore config
chore: update sonar-project.properties to reconfigure sonarqube scanning.
my changes
> CC-24280 Jenkins migration 2.4.2

- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/DebeziumEngineIT.java
- debezium-core/src/main/java/io/debezium/converters/CloudEventsConverter.java
- debezium-core/src/main/java/io/debezium/pipeline/signal/ExecuteSnapshot.java
- debezium-core/src/test/java/io/debezium/converters/CloudEventsConverterTest.java
- debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngine.java
- debezium-embedded/src/main/java/io/debezium/embedded/KafkaConnectUtil.java
- debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
- debezium-embedded/src/test/java/io/debezium/embedded/EmbeddedEngineTest.java
- pom.xml
Backporting this PR
https://github.com/debezium/debezium/pull/4617/files
as a part of
https://confluentinc.atlassian.net/browse/CC-24649
> kafka 3.5 changes

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/EventBuffer.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnection.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDatabaseSchema.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSnapshotChangeEventSource.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlStreamingChangeEventSource.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlValueConverters.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/AlterTableParserListener.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/AlterViewParserListener.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/CreateUniqueIndexParserListener.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerDatabaseSchema.java
- debezium-core/src/main/java/io/debezium/jdbc/JdbcValueConverters.java
https://docs.google.com/document/d/1UnsWty8NgWZDQg1GYTmBJvT-jVAOXeaQ9ByRyu6zegM/edit?usp=sharing
and
https://docs.google.com/document/d/1ksgcHZAaXK-uZuTlxQ03z9q-Z6nqR06w6QIgnwHHql4/edit?usp=sharing
contain the analysis for logging in debezium mysql and debezium sql server modules.
> Fix sensitive data logging

- pom.xml
https://confluentinc.atlassian.net/browse/CC-25311
> CC-25311: Bump postgresql driver version to 42.3.9

- pom.xml
https://confluentinc.atlassian.net/browse/CC-25311
> CC-25311: Bump postgresql driver version to 42.6.1

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlErrorHandler.java
https://confluentinc.atlassian.net/browse/CC-25657
> CC-25657 -- Fix retry of failed to read error

- debezium-server/debezium-server-redis/src/main/java/io/debezium/server/redis/RedisOffsetBackingStore.java
- pom.xml
Ref: https://confluentinc.atlassian.net/browse/CC-29435
> CC-29435: Bump the protobuf dependency to fix the CVE

- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/NotificationsIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresDefaultValueConverterIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresMetricsIT.java
- debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java
CherryPick : https://github.com/confluentinc/debezium/pull/111
> Move Postgres flush from OffsetCommitterThread to task-thread (poll())

- debezium-connector-binlog/src/main/java/io/debezium/connector/binlog/BinlogStreamingChangeEventSource.java
- debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogReaderSanitizeAuthenticationExceptionTest.java
History -- https://confluentinc.atlassian.net/browse/CCDB-3039
> Sanitize AuthenticationException error messages

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnector.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnector.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnector.java
- debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java
- debezium-core/src/main/java/io/debezium/util/Threads.java
- debezium-core/src/test/java/io/debezium/util/ThreadsTest.java
Cherry-picking https://github.com/debezium/debezium/pull/6381
> CC-32957: Cherry-pick DBZ-9004

- debezium-connector-binlog/src/main/java/io/debezium/connector/binlog/BinlogDatabaseSchema.java
- debezium-connector-binlog/src/main/java/io/debezium/connector/binlog/BinlogSnapshotChangeEventSource.java
- debezium-connector-binlog/src/main/java/io/debezium/connector/binlog/BinlogStreamingChangeEventSource.java
- debezium-connector-binlog/src/main/java/io/debezium/connector/binlog/EventBuffer.java
- debezium-connector-binlog/src/main/java/io/debezium/connector/binlog/jdbc/BinlogDefaultValueConverter.java
- debezium-connector-binlog/src/main/java/io/debezium/connector/binlog/jdbc/BinlogFieldReader.java
- debezium-connector-binlog/src/main/java/io/debezium/connector/binlog/jdbc/BinlogValueConverters.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/AlterTableParserListener.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/AlterViewParserListener.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/CreateUniqueIndexParserListener.java
- debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalDatabaseSchema.java
- debezium-core/src/main/java/io/debezium/util/Strings.java
This PR fixes the sensitive data logging happening in the debezium mysql connector. Specifically the `debezium-connector-binlog` and `debezium-connector-mysql` modules.
> CC-32477 - Fix sensitive data logging for debezium mysql

- debezium-core/src/main/java/io/debezium/pipeline/signal/actions/snapshotting/ExecuteSnapshot.java
This reverts https://github.com/debezium/debezium/pull/5899.
Rationale:
We are running Debezium 2.4 in Confluent Cloud and upgrading connectors in-place to Debezium 3.x. Some customer connectors may still be using the deprecated `additional-condition` config. Since this option was silently removed in v3, existing connectors relying on it would unexpectedly perform full table snapshots after upgrade.
To ensure a smoother transition, we're temporarily restoring `additional-condition` support with deprecation warnings to be followed in docs and customer communications.
https://confluentinc.atlassian.net/wiki/spaces/~635b68551cc605b1fd16afeb/pages/4445210510/CC-33853+Adding+additional-condition+back#Manual-Test-(Performed-on-mysql-cdc)
> CC-33853 -- Temporarily re-enable `additional-condition` for backward compatibility in Confluent Cloud

- debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogConnectorIT.java
- debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogDatabaseSchemaTest.java
- debezium-connector-binlog/src/test/java/io/debezium/relational/history/AbstractKafkaSchemaHistoryTest.java
- debezium-connector-binlog/src/test/java/io/debezium/relational/history/AbstractSchemaHistoryTest.java
- debezium-connector-mariadb/src/main/java/io/debezium/connector/mariadb/MariaDbConnectorTask.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/AlterViewParserListener.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresDefaultValueConverter.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgoutput/PgOutputMessageDecoder.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
- debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java
- debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java
- debezium-core/src/main/java/io/debezium/pipeline/ChangeEventSourceCoordinator.java
- debezium-core/src/main/java/io/debezium/pipeline/signal/actions/snapshotting/ExecuteSnapshot.java
- debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalDatabaseSchema.java
- debezium-core/src/main/java/io/debezium/relational/history/AbstractFileBasedSchemaHistory.java
- debezium-core/src/main/java/io/debezium/relational/history/AbstractSchemaHistory.java
- debezium-core/src/main/java/io/debezium/relational/history/SchemaHistory.java
- debezium-core/src/main/java/io/debezium/schema/HistorizedDatabaseSchema.java
- debezium-core/src/test/java/io/debezium/connector/common/BaseSourceTaskSnapshotModesValidationTest.java
- debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
- debezium-embedded/src/test/java/io/debezium/relational/history/AbstractSchemaHistoryTest.java
- debezium-storage/debezium-storage-kafka/src/main/java/io/debezium/storage/kafka/history/KafkaSchemaHistory.java
- debezium-storage/debezium-storage-tests/src/test/java/io/debezium/storage/AbstractSchemaHistoryTest.java
Cherry picks https://github.com/confluentinc/debezium/pull/140 which was targeted to v2 branch, to v3 branch.
✅ UT/IT passes
✅ Quick status transition happens
> Move schema history recovery out of task start

- debezium-core/src/main/java/io/debezium/relational/RelationalTableFilters.java
- debezium-core/src/main/java/io/debezium/relational/Tables.java
Details in https://confluentinc.atlassian.net/browse/CC-34473
✅ UTs/ITs pass
> [CC-34473] Implement caching in table inclusion filter

- debezium-storage/debezium-storage-kafka/src/main/java/io/debezium/storage/kafka/history/KafkaSchemaHistory.java
The recover function in KafkaSchemaHistory does the below in loop.
1. checks the end offset, compares with last seen end offset and prints a warn log in case these are different
2. polls topic for data and processes that data
Steps 1 and 2, both are executed in every iteration. Step 2, is the core recovery process, however step1 is an attempt to detect cases where the history topic is being shared amongst multiple connectors. On checking CPU profile in one of the cases where history recovery was in progress for a long history topic, i saw that CPU spent in step1 was more than step2, which is not intended.
To fix this and save some CPU cycles, we should not do step1 in every iteration. The CPU profile observed by me are attached here.
✅ UTs/ITs pass
> [CC-34742] Reduce calls to getEndOffset during kafka schema history recovery
