- debezium-core/src/main/java/io/debezium/relational/history/KafkaDatabaseHistory.java
- debezium-core/src/test/java/io/debezium/relational/history/KafkaDatabaseHistoryTest.java
Fix empty database history topic causes connector to fail after restart.
> CCDB-1063: Fix empty database history topic causes connector to fail.

- debezium-connector-mysql/pom.xml
Exclude generated code from jacoco plugin in mysql connector to avoid IncompatibleClassChangeError.
> Exclude generated code from jacoco plugin in mysql connector.

- pom.xml
Pulls in the changes from https://github.com/osheroff/mysql-binlog-connector-java/pull/27, which fixes https://github.com/osheroff/mysql-binlog-connector-java/issues/26, which made the connector impossible to use on Azure.
> RCCA-3187: Bump binlog reader dependency patch version

- debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java
Hit error. Also to make the access modifier consistent with upstream.
```
Caused by: java.lang.IllegalAccessError: class io.debezium.connector.mysql.MySqlConnectorConfig$$Lambda$1159/0x0000000802c36898 tried to access protected method 'int io.debezium.config.CommonConnectorConfig.validateServerNameIsDifferentFromHistoryTopicName(io.debezium.config.Configuration, io.debezium.config.Field, io.debezium.config.Field$ValidationOutput)' (io.debezium.connector.mysql.MySqlConnectorConfig$$Lambda$1159/0x0000000802c36898 and io.debezium.config.CommonConnectorConfig are in unnamed module of loader org.apache.kafka.connect.runtime.isolation.PluginClassLoader @5246f452)
at io.debezium.config.Field$Validator.lambda$and$0(Field.java:214)
at io.debezium.config.Field.validate(Field.java:545)
at …
```
> Make validateServerNameIsDifferentFromHistoryTopicName public.

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnector.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TestHelper.java
pgoutput is the standard logical decoding output plug-in in PostgreSQL 10+. This is not validated currently and the connector can weirdly fail during runtime with following trace:
```
io.debezium.jdbc.JdbcConnectionException: ERROR: syntax error
at io.debezium.connector.postgresql.connection.PostgresReplicationConnection.initPublication(PostgresReplicationConnection.java:180)
at io.debezium.connector.postgresql.connection.PostgresReplicationConnection.createReplicationSlot(PostgresReplicationConnection.java:343)
at io.debezium.connector.postgresql.PostgresConnectorTask.start(PostgresConnectorTask.java:125)
at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:103)
at org.apache.kafka.connect.runtime.WorkerSourceTask.initializeAndStart(WorkerSourceTask.java:235)
at …
```
> CCDB-4383: Validate server version for pgoutput plugin

- debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java
Problem
-----------
CCloud is currently at JDK version `OpenJDK 64-Bit Server VM, 16.0.2, 16.0.2+7-67` which has a [bug](https://bugs.openjdk.org/browse/JDK-8270056).
Jira: https://confluentinc.atlassian.net/browse/CCDB-5031
Solution
--------
Temporarily setting the access of the method `validateSkippedOperation` in super class to public to fix the error. Permanent fix would be to upgrade the JDK version that contains the fix. After applying the permanent fix, need to revert this change.
There was a slightly similar issue with Azure Blob Sink Connector which was fixed by adding -illegal-access=permit option to jvm args: https://github.com/confluentinc/cc-docker-connect/pull/1126
But this is not applicable for the current failure. Hence, making the access as public.
> CCDB-5031 Temporary fix for IllegalAccessError

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java
Adding a log line to print the number of change events processed in a single iteration for SqlServerCdc Source.
This is to come up with a default value for max.iteration.transactions, which needs to be set to prevent OOM.
> CCDB-5122: Log changes captured per iteration

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgoutput/PgOutputMessageDecoder.java
Cherry-picking the fix from the upstream: https://github.com/debezium/debezium/pull/4033
It is scheduled to release in 2.0.x version in upstream. Hence, adding to our fork separately for 1.9.6 version.
> DBZ-5792: Fix for - Message with LSN XYZ not present among LSNs seen

- debezium-bom/pom.xml
- debezium-core/pom.xml
- debezium-core/src/main/java/io/debezium/transforms/outbox/EventRouterConfigDefinition.java
- debezium-core/src/main/java/io/debezium/transforms/outbox/EventRouterDelegate.java
- debezium-core/src/test/java/io/debezium/transforms/outbox/EventRouterTest.java
The EventRouter bundles in the functionality of the RegexRouter. However RegexRouter uses backtracking based regex matching which is prone to ReDoS attacks and hence makes it unsuitable to be used on confluent cloud. 
re2j does a single linear scan of the regex pattern and hence is not affected by ReDoS attacks. We already use a version of regex router called TopicRegexRouter which replaces `java.util.regex` with re2j that we use on cloud. However the SMT is not bundled as an artefact separately and is part of cc-docker-connect. Instead of the code burden of maintaining an releasing TopicRegexRouter separately, its better to just replace the RegexRouter functionality here with re2j. 
re2j is not fully compatible with all the features of `java.util.regex` so we probably cannot move this to …
> CCLOG-2372: Use re2j in EventRouter SMT instead of RegexRouter

- debezium-core/src/main/java/io/debezium/relational/history/KafkaDatabaseHistory.java
Recovery attempts counter should be reset once we are able to successfully read some of the records from the database history topic.
> DBZ-6039: Reset history recovery attempt counter upon success

- Jenkinsfile
- debezium-connector-mysql/pom.xml
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/BlockingSnapshotIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/rest/DebeziumMySqlConnectorResourceIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/rest/DebeziumMySqlConnectorResourceNoDatabaseIT.java
- debezium-connector-postgres/pom.xml
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/rest/DebeziumPostgresConnectorResourceIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/rest/DebeziumPostgresConnectorResourceNoDatabaseIT.java
- debezium-connector-sqlserver/pom.xml
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/rest/DebeziumSqlServerConnectorResourceIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/rest/DebeziumSqlServerConnectorResourceNoDatabaseIT.java
- debezium-parent/pom.xml
- debezium-testing/debezium-testing-testcontainers/src/test/java/io/debezium/testing/testcontainers/ApicurioRegistryTest.java
- debezium-testing/debezium-testing-testcontainers/src/test/java/io/debezium/testing/testcontainers/ConnectorConfigurationTest.java
- debezium-testing/debezium-testing-testcontainers/src/test/java/io/debezium/testing/testcontainers/DebeziumContainerTest.java
- debezium-testing/debezium-testing-testcontainers/src/test/java/io/debezium/testing/testcontainers/MongoDbReplicaSetAuthTest.java
- debezium-testing/debezium-testing-testcontainers/src/test/java/io/debezium/testing/testcontainers/MongoDbReplicaSetTest.java
- pom.xml
1. Cherry-picked changes for JenkinsPipeline setup and dependency override of plexis-utils to ensure compatibility with Maven 3.9.
2. Updated MySQL Server Docker image version due to container initialization failures with the current version.
3. Modified BlockingSnapshotIT test-case to handle an additional variation of CREATE TABLE DDL.
4. Changed volumes definition in the SQL Server Docker image to fileSets to address missing SSL files at the specified path.
5. Disabled TestContainer-based tests as they were failing to connect with the TestContainer instance in Jenkins.
6. Disabled two tests in SqlServerConnectorIT to resolve failures causing the build to timeout.
> Enable jenkins pipeline and fix plexis-utils dependency

- .semaphore/project.yml
- .semaphore/semaphore.yml
- service.yml
Although the operation branches on this repo are v1.9.6-hotfix-x and v2.4.2-hotfix-x, for running periodic runs and twistlock scans on the branches, we need these files to be present on master. Most of the other workflows in the org work on the basis of these files being present in master.
Some relevant discussion here --
https://confluent.slack.com/archives/C09EP1SS3/p1705154543166019?thread_ts=1705137907.090639&cid=C09EP1SS3
> CC-24280 -- semaphore on master

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
- debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java
On cloud UI, topic prefix is present in the second page (Configuration) and connection related configs(server, username, password, etc) are present on the first page(Authentication). Due to this, when the validate call is made from the first page, it doesn't have table inclusion regex.
The problem is since table inclusion regex is not provided and it has no default value, the validation response contains only this message -- `The 'topic.prefix' value is invalid: A value is required`. But consider the case where there was a genuine issue on page1 configs, let's say the password was wrong. In this case also, the only validation error returned is the above one.
After the introduction of fail-fast validations, the requirement is to show the connectivity related errors on page1 itself. How …
> CC-27188 -- Remove topic prefix restriction of required field

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbSnapshotChangeEventSource.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSnapshotChangeEventSource.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSnapshotChangeEventSource.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/BlockingSnapshotIT.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerSnapshotChangeEventSource.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SchemaHistoryTopicIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
- debezium-core/src/main/java/io/debezium/pipeline/source/AbstractSnapshotChangeEventSource.java
- debezium-core/src/main/java/io/debezium/pipeline/source/SnapshottingTask.java
- debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java
- debezium-embedded/src/test/java/io/debezium/pipeline/AbstractBlockingSnapshotTest.java
The expected behaviour for the SQL Server CDC connector when `schema.history.internal.store.only.captured.tables.ddl` is set to its default value `false` is that schemas of all the tables are captured. However, due to a [bug](https://issues.redhat.com/browse/DBZ-7593), it is not currently happening.
The bug is fixed in version 2.5.3 of the connector. This change cherry-picks the [fix](https://github.com/debezium/debezium/pull/5357). However, due to some merge conflicts because of dependent changes, we are also including another [change](https://github.com/debezium/debezium/pull/5138).
- Existing tests passing
- Manually tested the change
- Upgrade testing done for before and after this change
> Cherry-pick DBZ-7593 and DBZ-7311

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnection.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSystemVariables.java
Some running connectors in prod have `database.connectionTimeZone` config value in mothership DB. Adding this to low-level configs could cause issues when the stored config in mothership db and the actual server timezone are different.
Adding a log to get the server time zone and the offset w.r.t UTC(GMT).
- Log output for Egypt Timezone:
`INFO [test-connector-2|task-0] The server time zone is EEST, and offset is 03:00:00 (io.debezium.connector.mysql.MySqlConnectorTask:93)`
- Log output for Singapore Timezone:
`INFO [test-connector-2|task-0] The server time zone is GMT+08, and offset is 08:00:00 (io.debezium.connector.mysql.MySqlConnectorTask:93)`
- Log output for America/New_York:
`INFO [test-connector-2|task-0] The server time zone is EDT, and offset is -4:00:00 …
> CC-20150: Add server time zone and offset log to Dbz MySql connector

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MysqlDefaultValueIT.java
- debezium-core/src/main/java/io/debezium/relational/RelationalDatabaseSchema.java
[CC-21893](https://confluentinc.atlassian.net/browse/CC-21893)
Currently, based on the table filters, if there are no tables to be captured, then the Debezium connectors after coming into RUNNING state would not perform any processing. There is simple a WARNING log stating 
> After applying the include/exclude list filters, no changes will be captured. Please check your configuration
This is making the users to get confused if there is any issue with the connector. 
With this change, the task will fail with the ConnectException such that the user will be notified with the error when there are no tables to be captured with the provided table filters which can be a regex. 
[CC-21893]: https://confluentinc.atlassian.net/browse/CC-21893?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTR …
> CC-21893 -- Fail task if there are no tables to capture from Table Filters

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlMetricsIT.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/metrics/SqlServerSnapshotPartitionMetrics.java
- debezium-core/src/main/java/io/debezium/pipeline/meters/SnapshotMeter.java
- debezium-core/src/main/java/io/debezium/pipeline/metrics/DefaultSnapshotChangeEventSourceMetrics.java
- debezium-core/src/main/java/io/debezium/pipeline/metrics/traits/SnapshotMetricsMXBean.java
- debezium-core/src/main/java/io/debezium/relational/history/SchemaHistoryMXBean.java
- debezium-core/src/main/java/io/debezium/relational/history/SchemaHistoryMetrics.java
- debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
[CC-27684](https://confluentinc.atlassian.net/browse/CC-27684) - Exposing the Debezium Metrics to customers via metrics API. As part of this ticket, exposing the Snapshot and Schema History metrics which would provide observability of the connector while in this phase.
As, these metrics are type BOOLEAN and STRING which are by default emitted by the Debezium. Currently, there is a issue while emitting these metrics as Otel Collector doesn't support STRING and BOOLEAN type metrics. Hence, converting these metrics to GAUGE_LONG in order to emit to Otel Collector and thus expose to customers via Metrics API>
[CC-27684]: https://confluentinc.atlassian.net/browse/CC-27684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Convert Debezium Snapshot & Schema Metrics to compatible for exposing

- debezium-core/src/main/java/io/debezium/transforms/ExtractNewRecordState.java
[CC-29686](https://confluentinc.atlassian.net/browse/CC-29686) - Adding all the Dependent Configurations in the config method of Extract New Record State SMT.
[CC-29686]: https://confluentinc.atlassian.net/browse/CC-29686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CC-29686: Add all dependent configurations for Extract New Record State SMT

- debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java
JIRA -> https://confluentinc.atlassian.net/browse/CC-30994
```
since commit() is just like a scheduled-invocation, it now updates a flag instead on every OffsetCommitInterval. Task-thread will perform producer.commit()  now
```
> Move Postgres flush from OffsetCommitterThread to task-thread (poll())

- debezium-core/src/main/java/io/debezium/pipeline/JmxUtils.java
- documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-configuration-database-history-properties.adoc
Adding this to the logs to track what is the name of the MBean that it is failing to register. We already see errors logs while trying to unregister some mbeans, adding this will help track if they are the same mbeans.
See the comments on the JIRA https://confluentinc.atlassian.net/browse/CC-28776 for additional details.
> CC-28776: add MBean name when failing to register it

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDatabaseSchemaTest.java
- debezium-connector-mysql/src/test/java/io/debezium/relational/history/AbstractSchemaHistoryTest.java
- debezium-connector-mysql/src/test/java/io/debezium/relational/history/KafkaSchemaHistoryTest.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerDatabaseSchema.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
- debezium-core/src/main/java/io/debezium/pipeline/ChangeEventSourceCoordinator.java
- debezium-core/src/main/java/io/debezium/pipeline/spi/Offsets.java
- debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalDatabaseSchema.java
- debezium-core/src/main/java/io/debezium/relational/history/AbstractFileBasedSchemaHistory.java
- debezium-core/src/main/java/io/debezium/relational/history/AbstractSchemaHistory.java
- debezium-core/src/main/java/io/debezium/relational/history/SchemaHistory.java
- debezium-core/src/main/java/io/debezium/schema/HistorizedDatabaseSchema.java
- debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
- debezium-embedded/src/test/java/io/debezium/relational/history/AbstractSchemaHistoryTest.java
- debezium-storage/debezium-storage-kafka/src/main/java/io/debezium/storage/kafka/history/KafkaSchemaHistory.java
Described [here](https://confluentinc.atlassian.net/wiki/spaces/~635b68551cc605b1fd16afeb/pages/4364895962/WIP+Solutions+to+SH+problem#Solution-1)
TLDR;
The implemtnatation of `start` method from the `SourceTask` interface for the mysql cdc connector conditionally can take a lot of time. This time is accounted for the large schema history recovery time. In such cases, due to continuous operator restarts fatal symptoms like thread leaks, high cpu usage, zombie tasks are observed.
To solve this, we are moving the schema history recovery part after the `start` method is complete. By doing this, we are making the implementation of `start` lightweight, which follows the "unsaid" contract. Also the above mentioned issues would no more be present. …
> CC-33244 -- Move schema history recovery out of the task start

- debezium-connector-binlog/src/main/java/io/debezium/connector/binlog/BinlogStreamingChangeEventSource.java
- debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogConvertingFailureIT.java
- debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogReaderSanitizeAuthenticationExceptionTest.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnector.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorTest.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresDefaultValueConverterIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TestHelper.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/util/TestHelper.java
- debezium-core/src/main/java/io/debezium/config/Configuration.java
- debezium-core/src/main/java/io/debezium/connector/common/RelationalBaseSourceConnector.java
- debezium-core/src/main/java/io/debezium/pipeline/meters/SnapshotMeter.java
- debezium-core/src/main/java/io/debezium/relational/history/SchemaHistoryMetrics.java
- debezium-core/src/main/java/io/debezium/transforms/outbox/EventRouterDelegate.java
- debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
maven commands usually run formatting and linting by default. This leads to some unknown files getting changed which leads to productivity loss. Developer has to manually rollback those changes since they are always unrelated to the change.
This PR is about committing those changes in the branch so that in future only relevant lint and formatting changes are applied on using maven commands.
> Fix lint and formatting

- debezium-connector-mariadb/src/main/java/io/debezium/connector/mariadb/antlr/MariaDbAntlrDdlParser.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/MySqlAntlrDdlParser.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/antlr/OracleDdlParser.java
- debezium-ddl-parser/src/main/java/io/debezium/antlr/AntlrDdlParser.java
This one is implementing [this](https://confluentinc.atlassian.net/wiki/spaces/~635b68551cc605b1fd16afeb/pages/4483842738/Database+Schema+History+Recovery+Optimization+Analysis#Optimization-2-%E2%80%93-DataTypeResolver-instantiation-in-every-parse-path) optimization for the schema history recovery codepath.
We saw that the recovery time for our repro decreased from 20 seconds to 16 seconds after this change.
✅ UTs/ITs pass
> CC-34744 Remove redundancy in intializing DataTypeResolver

- debezium-connector-binlog/src/main/java/io/debezium/connector/binlog/BinlogStreamingChangeEventSource.java
- debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogSchemaHistoryIT.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlStreamingChangeEventSource.java
This PR adds test to ensure that TRUNCATE events are not stored in the history topic. This should be true for both possible cases with `skipped.operations`. One which includes truncate and the other case where it doesn't include.
✅ UTs/ITs
> CC-34771 Add test for filtering out truncate from history topic

- debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java
In incremental screenshots, if TCP connection gets broken in between connector pod and MySQL source for any reason, the connector would fail throwing SQL exception. Although there was a logic for connection validation before statement execute, but if during execute, the connection would break, the end user would get exception, making there connector stop. They needed to manually restart it to get it processing. Ref: #inc-2918_neema-mysqlcdcsourcev2-snapshot-system-stops-working-after-the-db-
We are just proposing a single retry to re-establish connection, and execute statement if statement execution fails with `SQLRecoverableException` or `SQLNonTransientConnectionException`.
https://confluent.slack.com/archives/C090HS8C0M7/p1753084485125149
> CC-34585 Fix usage of cached prepared statement in `emitWindowOpen`

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/snapshot/lock/ExclusiveSnapshotLock.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/snapshot/lock/NoSnapshotLock.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/snapshot/query/SelectAllSnapshotQuery.java
Post DBZ v3 upgrade, the SQL Server connectors have started to log below warning
```
Found a not connector specific implementation io.debezium.connector.v2.sqlserver.snapshot.lock.ExclusiveSnapshotLock for lock mode exclusive
```
In v3, the connector uses ServiceLoader to load all available `SnapshotQuery` and `SnapshotLock` implementations during runtime. There are following checks 
- Confirm if the value in the configuration matches the name in the known implementations as well as the `connector.class` in the configuration matches the connector class the implementation is annotated with `@ConnectorSpecific`.
- Confirm if the name of the configured value (`snapshot.locking.mode=exclusive`) matches the name in the known implementations (`ExclusiveSnapshotLock.java`) (fallback check)
The …
> CC-35215: Fixes `Found a not connector specific implementation`warn

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerIncrementalSnapshotContext.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerOffsetContext.java
- debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotContext.java
- debezium-core/src/main/java/io/debezium/relational/TableId.java
- debezium-core/src/test/java/io/debezium/relational/TableIdTest.java
This PR cherry-picks changes done as part of [DBZ-9209](https://issues.redhat.com/browse/DBZ-9209)
Upstream PR: https://github.com/debezium/debezium/pull/6581
Currently, the incremental snapshot updates the offsets such that the table name is stored as well in the offsets. If the tablename contains a special character, there is a chance the task fails to parse the tablename post restart and is unable to recover.
In order to fix that, the SQL Server incremental snapshot context is overridden to wrap the `catalogName.schemaName.tableName` written to and read from the offsets in brackets i.e. `[catalogName].[schemaName].[tableName]`. Large brackets `[` ,`] `are acceptable start and end delimiters in SQL Server. Hence, the DBZ already has support for these characters for SQL server. After …
> CC-34772: Connector failing to restart due to special table in Incremental snapshot
